In [11]:
import numpy as np

- 매트릭스는 행렬, 행으로 한줄은 벡터로 정의

\begin{equation}
\begin{bmatrix}
1 & 4 & 2 & 0 \\
9 & 5 & 0 & 0 \\
4 & 0 & 2 & 4 \\
6 & 1 & 8 & 3
\end{bmatrix}
\begin{bmatrix}
1\\2\\3\\4
\end{bmatrix}=?
\end{equation}

In [17]:
a=np.matrix('1,4,2,0;9,5,0,0;4,0,2,4;6,1,8,3')
x=np.matrix('1;2;3;4')

b=np.array([[1,4,2,0],[9,5,0,0],[4,0,2,4],[6,1,8,3]])
y=np.array([1,2,3,4])



print(a)
print(x)
print(b)
print(y)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]
[[1]
 [2]
 [3]
 [4]]
[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]
[1 2 3 4]


\begin{equation}
\begin{bmatrix}
4 & 5 & 2 & 1 \\
2 & 3 & 8 & 0 \\
1 & 0 & 7 & 2
\end{bmatrix}
\begin{bmatrix}
1\\2\\3\\4
\end{bmatrix}=?
\end{equation}

In [18]:
c=np.array([[1],[2],[3],[4]])
print(c)

[[1]
 [2]
 [3]
 [4]]


In [19]:
## 내적 : 행렬곱 : array가 아닌 matrix이므로 내적곱을 for 문으로 정리 구해야 함
ret = np.zeros((4,1))
n = 4
for i in range(0,n): # 행을 나타냄 새로로 나열되니깐 행의 구분자가 됨
    val = 0.0
    for j in range(0,n):
        val += a[i,j]*x[j]
    ret[i] = val
  
print(ret)

[[15.]
 [19.]
 [26.]
 [44.]]


In [29]:
# array는 그냥 곱하면 행렬곱이 된다 벡터형태로 나오려면 아래의 for 문을 돌려야 하며 행렬형태는 가로로 더하면 백터와 같은 값이 된다
print(b*y)

# 그래서 arry는 아래와 같이 처리한다 둘다 동일한 결과 같이 나온다
np.dot(b,y)
np.matmul(b,y)

[[ 1  8  6  0]
 [ 9 10  0  0]
 [ 4  0  6 16]
 [ 6  2 24 12]]


array([15, 19, 26, 44])

In [23]:
## 내적 : 행렬곱 : array가 아닌 matrix이므로 내적곱을 for 문으로 정리 구해야 함
ret = np.array([0,0,0,0])
n = 4
for i in range(0,n): # 행을 나타냄 새로로 나열되니깐 행의 구분자가 됨
    val = 0.0
    for j in range(0,n):
        val += b[i,j]*y[j]
    ret[i] = val
  
print(ret)

[15 19 26 44]


In [41]:
b=np.array([[4,5,2,1],[2,3,8,0],[1,0,7,2]])
y=np.array([1,2,3,4])

ret = np.array([0,0,0])
n = 3
for i in range(0,n): # 행을 나타냄 새로로 나열되니깐 행의 구분자가 됨
    val = 0.0
    for j in range(0,n):
        val += b[i,j]*y[j]
    ret[i] = val
  
print(ret)

[20 32 22]


In [39]:
# 그래서 arry는 아래와 같이 처리한다 둘다 동일한 결과 같이 나온다
np.dot(b,y)
np.matmul(b,y)

array([24, 32, 30])